### ISSUE TITLE
rechit relval todo

### ISSUE THREAD

**Issue by slowmoyang** [slowmoyang/workspace-rpc#10]
- [ ] remove 2d residual and pull 
- [ ] add 1d residual and pull
- [ ] remove mean and standard deviation
